
package com.baidu.google;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserDao", targetNamespace = "http://dao.itcast.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.baidu.google.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByid", targetNamespace = "http://dao.itcast.com/", className = "com.baidu.google.FindUserByid")
    @ResponseWrapper(localName = "findUserByidResponse", targetNamespace = "http://dao.itcast.com/", className = "com.baidu.google.FindUserByidResponse")
    @Action(input = "http://dao.itcast.com/UserDao/findUserByidRequest", output = "http://dao.itcast.com/UserDao/findUserByidResponse")
    public User findUserByid(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://dao.itcast.com/", className = "com.baidu.google.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://dao.itcast.com/", className = "com.baidu.google.AddResponse")
    @Action(input = "http://dao.itcast.com/UserDao/addRequest", output = "http://dao.itcast.com/UserDao/addResponse")
    public void add();

}
