
package com.itcast.dao;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserDao", targetNamespace = "http://dao.itcast.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserDao {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://dao.itcast.com/", className = "com.itcast.dao.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://dao.itcast.com/", className = "com.itcast.dao.AddResponse")
    @Action(input = "http://dao.itcast.com/UserDao/addRequest", output = "http://dao.itcast.com/UserDao/addResponse")
    public void add();

}
